### ISSUE TITLE
[🎨 Style] 편지지 선택 화면 

### ISSUE THREAD

**Issue by Tnalxmsk** [Tnalxmsk/dear-front#10]
## ✅ Description

편지지 선택 Flow 구현

## ✔️ TODO
- [x] Progressbar 컴포넌트 구현
- [x] 편지지 컴포넌트 구현
- [x] 편지지 선택 화면 구현
