### ISSUE TITLE
[🎨style] 받은 편지 UI 구현

### ISSUE THREAD

**Issue by 3tjwls7** [Tnalxmsk/dear-front#14]
## ✅ Description
받은 편지 UI 구현
## ✔️ TODO
- [x] 받은 편지 제목, 내용, 수신자, 송신자 등 구현
- [x] 줄노트 편지지 다른 편지지로 교체
- [x] 반응형 구현
- [x] 최신순 버튼 구현
- [x] from, dear, 나에게 쓴 편지에 따라 우편함에서 다르게 표시
