### ISSUE TITLE
[🎨style] 우편함, 상세 페이지(받은 편지 내용) 구현

### ISSUE THREAD

**Issue by 3tjwls7** [Tnalxmsk/dear-front#5]
## ✅ Description
편지함, 받은 편지 UI 구현
## ✔️ TODO
- [x] 받은 편지 UI 구현
- [x] 편지함 비율 수정
- [x] 우편함 디자인 수정
- [x] 종류별로 구분되는 우편함 구현
- [x] 편지 즐겨찾기 구현
- [x] 편지함 반응형으로 수정
- [x] 편지 제목 id로 파라미터 전송
