### ISSUE TITLE
[🎨style] 편지 작성 페이지 화면 UI 구현 

### ISSUE THREAD

**Issue by tmdcks1103** [Tnalxmsk/dear-front#8]
## ✅ Description
편지 작성 UI 구현

## ✔️ TODO
- [x] 전체적인 편지 작성 UI 구현
- [x] Dear, From 문구 포함 
- [ ] 이미지 항목 삽입

**Comment by tmdcks1103** [comment]
.
